### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Srichitra-S** [fanq15/FewX#21]
This error comes up while running all.sh

**Comment by fanq15** [comment]
Could you paste more error information?

**Comment by Srichitra-S** [comment]
Traceback (most recent call last):
  File "fsod_train_net.py", line 14, in <module>
    from detectron2.engine import DefaultTrainer, default_argument_parser, default_setup, launch
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/__init__.py", line 11, in <module>
    from .hooks import *
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/hooks.py", line 17, in <module>
    from detectron2.evaluation.testing import flatten_results_dict
  File "/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/__init__.py", line 2, in <module>
    from .cityscapes_evaluation import CityscapesInstanceEvaluator, CityscapesSemSegEvaluator
  File "/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/cityscapes_evaluation.py", line 11, in <module>
    from detectron2.data import MetadataCatalog
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/usr/local/lib/python3.6/dist-packages/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "/usr/local/lib/python3.6/dist-packages/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "/usr/local/lib/python3.6/dist-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/usr/local/lib/python3.6/dist-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by cp1108** [comment]
I also encountered this problem. Have you solved it?
