### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by zhzhzhzhzhzh** [fanq15/FewX#27]
when I run all.sh,there was a error: TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

whole message as follow:
 
Rank of current process: 0. World size: 2
Traceback (most recent call last):
  File "fsod_train_net.py", line 118, in <module>
    args=(args,),
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/home/ubuntu/FewX/fsod_train_net.py", line 94, in main
    cfg = setup(args)
  File "/home/ubuntu/FewX/fsod_train_net.py", line 85, in setup
    default_setup(cfg, args)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 132, in default_setup
    logger.info("Environment info:\n" + collect_env_info())
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/detectron2/utils/collect_env.py", line 136, in collect_env_info
    msg = " - invalid!" if not os.path.isdir(CUDA_HOME) else ""
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by fanq15** [comment]
Please use this code to install detectron2: 
```
python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
```
The error is derived from the mismatch between detection 1.5 and 1.7.

**Comment by zhzhzhzhzhzh** [comment]
> Please use this code to install detectron2:
> 
> ```
> python -m pip install detectron2 -f \
>   https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
> ```
> 
> The error is derived from the mismatch between detectron2 1.5 and 1.7.
