### ISSUE TITLE
how to get 12 map？

### ISSUE THREAD

**Issue by zr526799544** [fanq15/FewX#28]
I run all.sh and get nothing. so I use detetron demo predict code to generate the coco result and the resulte is to low.loading annotations into memory...
Done (t=0.50s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.38s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=11.88s).
Accumulating evaluation results...
DONE (t=2.87s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.011
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.020
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.010
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.006
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.023
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.027
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.032
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.032
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.010
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.071

**Comment by fanq15** [comment]
Could send me your training log?

**Comment by zr526799544** [comment]
> Could send me your training log?

I do not train the model  I just test it on coco val use the weight you provided.

**Comment by zr526799544** [comment]
> Could send me your training log?

the code I run has been send to you email.

**Comment by fanq15** [comment]
What's your detectron2 version?

**Comment by zr526799544** [comment]
> What's your detectron2 version?

0.3

**Comment by fanq15** [comment]
Please try this one to install detectron2 0.1 version
```
python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
```

**Comment by zr526799544** [comment]
> Please try this one to install detectron2 0.1 version
> 
> ```
> python -m pip install detectron2 -f \
>   https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
> ```

YOU install MD said that recommend the Pre-Built Detectron2 (Linux only) version with pytorch 1.5. I use the Pre-Built Detectron2 with CUDA 10.1 and pytorch 1.5. and  I found detectron2  V0.1 just for pytorch 1.4 and  use python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html can just install V0.3.

**Comment by zr526799544** [comment]
> Please try this one to install detectron2 0.1 version
> 
> ```
> python -m pip install detectron2 -f \
>   https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
> ```

I can just use V0.1.3

**Comment by zr526799544** [comment]
/workspace/FewX-master/fewx/modeling/fsod/fsod_roi_heads.py in <module>()
      8 
      9 from detectron2.config import configurable
---> 10 from detectron2.layers import ShapeSpec, nonzero_tuple
     11 from detectron2.structures import Boxes, ImageList, Instances, pairwise_iou
     12 from detectron2.utils.events import get_event_storage

ImportError: cannot import name 'nonzero_tuple'

> Please try this one to install detectron2 0.1 version
> 
> ```
> python -m pip install detectron2 -f \
>   https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
> ```

/workspace/FewX-master/fewx/modeling/fsod/fsod_roi_heads.py in <module>()
      8 
      9 from detectron2.config import configurable
---> 10 from detectron2.layers import ShapeSpec, nonzero_tuple
     11 from detectron2.structures import Boxes, ImageList, Instances, pairwise_iou
     12 from detectron2.utils.events import get_event_storage

ImportError: cannot import name 'nonzero_tuple'

**Comment by fanq15** [comment]
I tried the evaluation again and I can get the reported number.

```
[12/30 18:13:39 fewx.evaluation.coco_evaluation]: Preparing results for COCO format ...
[12/30 18:13:39 fewx.evaluation.coco_evaluation]: Saving results to ./output/fsod/finetune_dir/R_50_C4_1x/inference/coco_instances_results.json
[12/30 18:13:39 fewx.evaluation.coco_evaluation]: Evaluating predictions ...
Loading and preparing results...
DONE (t=0.13s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
COCOeval_opt.evaluate() finished in 10.44 seconds.
Accumulating evaluation results...
COCOeval_opt.accumulate() finished in 1.24 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.030
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.056
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.029
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.007
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.031
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.052
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.047
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.066
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.066
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.009
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.059
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.114
[12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for bbox: 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|
| 2.989 | 5.592  | 2.948  | 0.724 | 3.057 | 5.165 |
[12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP  : 11.95
[12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP50: 22.37
[12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP75: 11.79
[12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APs : 2.89
[12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APm : 12.23
[12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APl : 20.66
```

**Comment by zr526799544** [comment]
> I tried the evaluation again and I can get the reported number.
> 
> ```
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Preparing results for COCO format ...
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Saving results to ./output/fsod/finetune_dir/R_50_C4_1x/inference/coco_instances_results.json
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Evaluating predictions ...
> Loading and preparing results...
> DONE (t=0.13s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> COCOeval_opt.evaluate() finished in 10.44 seconds.
> Accumulating evaluation results...
> COCOeval_opt.accumulate() finished in 1.24 seconds.
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.030
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.056
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.029
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.007
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.031
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.052
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.047
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.066
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.066
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.009
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.059
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.114
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for bbox: 
> |  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
> |:-----:|:------:|:------:|:-----:|:-----:|:-----:|
> | 2.989 | 5.592  | 2.948  | 0.724 | 3.057 | 5.165 |
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP  : 11.95
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP50: 22.37
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP75: 11.79
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APs : 2.89
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APm : 12.23
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APl : 20.66
> ```

you env is pytorch 1.5 . detectron2 v0.31 ? just run all.sh can get the result?

**Comment by zr526799544** [comment]
> I tried the evaluation again and I can get the reported number.
> 
> ```
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Preparing results for COCO format ...
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Saving results to ./output/fsod/finetune_dir/R_50_C4_1x/inference/coco_instances_results.json
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Evaluating predictions ...
> Loading and preparing results...
> DONE (t=0.13s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> COCOeval_opt.evaluate() finished in 10.44 seconds.
> Accumulating evaluation results...
> COCOeval_opt.accumulate() finished in 1.24 seconds.
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.030
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.056
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.029
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.007
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.031
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.052
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.047
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.066
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.066
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.009
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.059
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.114
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for bbox: 
> |  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
> |:-----:|:------:|:------:|:-----:|:-----:|:-----:|
> | 2.989 | 5.592  | 2.948  | 0.724 | 3.057 | 5.165 |
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP  : 11.95
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP50: 22.37
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP75: 11.79
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APs : 2.89
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APm : 12.23
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APl : 20.66
> ```
If I run all.sh to evaluate the model all I get just this and end.
[12/30 22:20:19 fewx.modeling.fsod.fsod_rcnn]: =========== Offline support features are generated. ===========
[12/30 22:20:19 fewx.modeling.fsod.fsod_rcnn]: ============ Few-shot object detetion will start. =============

**Comment by zr526799544** [comment]
> I tried the evaluation again and I can get the reported number.
> 
> ```
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Preparing results for COCO format ...
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Saving results to ./output/fsod/finetune_dir/R_50_C4_1x/inference/coco_instances_results.json
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Evaluating predictions ...
> Loading and preparing results...
> DONE (t=0.13s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> COCOeval_opt.evaluate() finished in 10.44 seconds.
> Accumulating evaluation results...
> COCOeval_opt.accumulate() finished in 1.24 seconds.
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.030
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.056
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.029
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.007
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.031
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.052
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.047
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.066
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.066
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.009
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.059
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.114
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for bbox: 
> |  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
> |:-----:|:------:|:------:|:-----:|:-----:|:-----:|
> | 2.989 | 5.592  | 2.948  | 0.724 | 3.057 | 5.165 |
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP  : 11.95
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP50: 22.37
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP75: 11.79
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APs : 2.89
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APm : 12.23
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APl : 20.66
> ```
in your code fewx/modeling/fsod/fsod_rcnn.py 314   there is  sys.exit(0)   I don't understand why. so I just delete it and meet 
[12/31 01:24:21 fewx.modeling.fsod.fsod_rcnn]: ===========inference call===========
Traceback (most recent call last):
  File "fsod_train_net.py", line 121, in <module>
    args=(args,),
  File "/opt/conda/envs/21de/lib/python3.6/site-packages/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/opt/conda/envs/21de/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/21de/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/conda/envs/21de/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/21de/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/opt/conda/envs/21de/lib/python3.6/site-packages/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/workspace/FewX-master/fsod_train_net.py", line 103, in main
    res = Trainer.test(cfg, model)
  File "/opt/conda/envs/21de/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 516, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/opt/conda/envs/21de/lib/python3.6/site-packages/detectron2/evaluation/evaluator.py", line 141, in inference_on_dataset
    outputs = model(inputs)
  File "/opt/conda/envs/21de/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/FewX-master/fewx/modeling/fsod/fsod_rcnn.py", line 128, in forward
    return self.inference(batched_inputs)
  File "/workspace/FewX-master/fewx/modeling/fsod/fsod_rcnn.py", line 350, in inference
    for cls_id, res4_avg in self.support_dict['res4_avg'].items():
  File "/opt/conda/envs/21de/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'FsodRCNN' object has no attribute 'support_dict'

**Comment by zr526799544** [comment]
> I tried the evaluation again and I can get the reported number.
> 
> ```
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Preparing results for COCO format ...
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Saving results to ./output/fsod/finetune_dir/R_50_C4_1x/inference/coco_instances_results.json
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Evaluating predictions ...
> Loading and preparing results...
> DONE (t=0.13s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> COCOeval_opt.evaluate() finished in 10.44 seconds.
> Accumulating evaluation results...
> COCOeval_opt.accumulate() finished in 1.24 seconds.
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.030
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.056
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.029
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.007
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.031
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.052
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.047
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.066
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.066
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.009
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.059
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.114
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for bbox: 
> |  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
> |:-----:|:------:|:------:|:-----:|:-----:|:-----:|
> | 2.989 | 5.592  | 2.948  | 0.724 | 3.057 | 5.165 |
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP  : 11.95
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP50: 22.37
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP75: 11.79
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APs : 2.89
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APm : 12.23
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APl : 20.66
> ```

I find the problem..... In your all.sh you do delete the ./support_dir/support_feature.pkl which inference needed ... plz delete it in your all.sh

**Comment by zr526799544** [comment]
> I tried the evaluation again and I can get the reported number.
> 
> ```
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Preparing results for COCO format ...
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Saving results to ./output/fsod/finetune_dir/R_50_C4_1x/inference/coco_instances_results.json
> [12/30 18:13:39 fewx.evaluation.coco_evaluation]: Evaluating predictions ...
> Loading and preparing results...
> DONE (t=0.13s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> COCOeval_opt.evaluate() finished in 10.44 seconds.
> Accumulating evaluation results...
> COCOeval_opt.accumulate() finished in 1.24 seconds.
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.030
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.056
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.029
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.007
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.031
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.052
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.047
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.066
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.066
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.009
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.059
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.114
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for bbox: 
> |  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
> |:-----:|:------:|:------:|:-----:|:-----:|:-----:|
> | 2.989 | 5.592  | 2.948  | 0.724 | 3.057 | 5.165 |
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP  : 11.95
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP50: 22.37
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP75: 11.79
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APs : 2.89
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APm : 12.23
> [12/30 18:13:51 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APl : 20.66
> ```

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.019
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.035
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.019
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.009
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.041
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.036
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.041
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.041
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.096
[12/31 01:46:01 fewx.evaluation.coco_evaluation]: Evaluation results for bbox: 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|
| 1.939 | 3.469  | 1.948  | 0.015 | 0.889 | 4.124 |
[12/31 01:46:01 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP  : 7.75
[12/31 01:46:01 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP50: 13.88
[12/31 01:46:01 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> AP75: 7.79
[12/31 01:46:01 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APs : 0.06
[12/31 01:46:01 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APm : 3.56
[12/31 01:46:01 fewx.evaluation.coco_evaluation]: Evaluation results for VOC 20 categories =======> APl : 16.50

**Comment by Zhang1Sheng** [comment]
![(FNMNJ28(96TBAT}RV1 4K](https://user-images.githubusercontent.com/51778165/114492121-72a71e80-9c4a-11eb-8909-0c89452ce237.png)
I know that the model generates 100 BBoxes for each class, but when I predicted that only dozens of BBoxes were generated for each class. Why not 100 and how to solve this problem?
