### ISSUE TITLE
No such file or directory: './support_dir/support_feature.pkl'

### ISSUE THREAD

**Issue by lllying** [fanq15/FewX#9]
Thanks for your code! but I meet this error when I run your code on COCO dataset, could you please tell me what is this file for？and where could I get it？It seems that the file，train_support_df.pkl，and  10_shot_support_df.pkl organize the support data, so I'm confused about this error.

[08/18 14:15:37 d2.evaluation.evaluator]: Start inference on 5000 images
/home/ly/anaconda3/envs/py3_torch151/lib/python3.7/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Traceback (most recent call last):
  File "fsod_train_net.py", line 118, in <module>
    args=(args,),
  File "/home/ly/anaconda3/envs/py3_torch151/lib/python3.7/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "fsod_train_net.py", line 101, in main
    res = Trainer.test(cfg, model)
  File "/home/ly/anaconda3/envs/py3_torch151/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 516, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/ly/anaconda3/envs/py3_torch151/lib/python3.7/site-packages/detectron2/evaluation/evaluator.py", line 141, in inference_on_dataset
    outputs = model(inputs)
  File "/home/ly/anaconda3/envs/py3_torch151/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ly/few-shot-object-detection/FewX-master/fewx/modeling/fsod/fsod_rcnn.py", line 126, in forward
    self.init_model()
  File "/home/ly/few-shot-object-detection/FewX-master/fewx/modeling/fsod/fsod_rcnn.py", line 302, in init_model
    with open(support_file_name, 'wb') as f:

FileNotFoundError: [Errno 2] No such file or directory: './support_dir/support_feature.pkl'

**Comment by fanq15** [comment]
[finetune training](https://github.com/fanq15/FewX/blob/239d39cc2000495fa9d23d97a375a3cbfb719d74/all.sh#L10) will generate the suppoer_feature.pkl.

**Comment by lllying** [comment]
Problem solved！ Thank you so much！

**Comment by fresh-professor** [comment]
Hello. I still have this problem.
when I ran this code, it never made the support_feature.pkl...
(even ./support_dir/)

**Comment by fanq15** [comment]
Bug fixed.

**Comment by woodyXwt** [comment]
I ran into the same problem, even if I manually created ‘support_dir’, it couldn’t solve the problem
